In [10]:
import numpy as np
print(np.__version__)

1.26.4


Conclusion:
The number of rows and columns doesn’t determine ndim.It’s the number of nested brackets (axes/levels) that matters. 

Example:np.array() 0ndim
Example:np.array([ ]) 1ndim
Example:np.array([[  ]] 2ndim
Example:np.array([[[ ]]]) 3ndim
Example : np.array([[[[ ]]]]) 4ndim

In [2]:
import numpy as np
arr1 = np.array(10)
arr2 = np.array([1,2,3,4,5,7]) #create a numpy array list structure by passing the values in list format #
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]],[[4,5,6],[6,7,8],[7,8,9]]) # using nested list to create a numpy array matrices like structure #
print(arr1)
print(arr2)
print(arr3)

TypeError: Field elements must be 2- or 3-tuples, got '[4, 5, 6]'

In [4]:
arr22 = np.array([[3,4,5],[4,5,6],[7,8,9],[3,4,5]])

In [14]:
arr22.ndim

2

In [12]:
arr22.size

12

In [16]:
arr22.shape

(4, 3)

In [26]:
arr22.reshape(2,2,3)

array([[[3, 4, 5],
        [4, 5, 6]],

       [[7, 8, 9],
        [3, 4, 5]]])

In [342]:
arr23=np.array([[2,2],[3,4],[5,6],[7,8],[4,5],[4,3],[3,5],[5,6]])

In [346]:
print(arr23.shape,arr23.size)
arr23

(8, 2) 16


array([[2, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [4, 5],
       [4, 3],
       [3, 5],
       [5, 6]])

In [356]:
z1=arr23.reshape(2,2,2,2) # 2 blocks, 2 sub-blocks, 2 ROWS , 2 COLUMNS #
z1

array([[[[2, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]],


       [[[4, 5],
         [4, 3]],

        [[3, 5],
         [5, 6]]]])

In [360]:
z1.ndim

4

In [362]:
print(z1)

[[[[2 2]
   [3 4]]

  [[5 6]
   [7 8]]]


 [[[4 5]
   [4 3]]

  [[3 5]
   [5 6]]]]


In [295]:
print(arr3.shape,arr3.size,arr3.dtype,arr3.ndim)

(3, 3) 9 int64 2


In [34]:
#Homework -Creat a numpy array from a set and dictionary #
arr4 = np.array({1,2,3,4,5,6})
print(arr4)

{1, 2, 3, 4, 5, 6}


In [68]:
#Homework -Creat a numpy array from dictionary #
arr5 = np.array({'john':1,'mike':2,'smith':3})
print(arr5) #While deifining nested sets,we should enclose the values inside list like format to return the results)

{'john': 1, 'mike': 2, 'smith': 3}


In [44]:
type(arr5)

numpy.ndarray

In [70]:
arr6 = np.array({'john':1,'mike':2,'smith':3},{'Karen':4,'oliver':5,'kate':6})
print(arr6) #While deifining nested dict,we should enclose the values inside list like format to return the results)

TypeError: object of type 'int' has no len()

In [388]:
#Numpy with list dataset #
import numpy as np

py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

print("Original List:", py_list)
print("NumPy Array:", np_array)
print("Mean:", np.mean(np_array))

Original List: [1, 2, 3, 4, 5]
NumPy Array: [1 2 3 4 5]
Mean: 3.0


In [66]:
arr7 = np.array({'john':1,'mike':2,'smith':3})
print(arr7)

{'john': 1, 'mike': 2, 'smith': 3}


Similiar to pandas on how we do a quick overview of the data using df.info,df.shape,df.describe,df.dtypes,df.size
There are similair commands in numpy where we use the following commands to get the overview of the data using below commands

1.type(arr) - will tell the datatype of the variable as a whole - We use type() funtion in python.
2.arr.shape -will tell the no of rows and columns
3.arr.size - will tell the total no of elements in the array
4.arr.ndim - will tell how many dimensions of the array data is 
5.arr.dtype -arr.dtype - will tell the datatype of elements inside it

In [80]:
print(arr1.shape,arr1.size,arr1.ndim,arr1.dtype)

() 1 0 int64


In [82]:
print(arr2.shape,arr2.size,arr2.ndim,arr2.dtype)

(6,) 6 1 int64


In [84]:
print(arr3.shape,arr3.size,arr3.ndim,arr3.dtype)

(3, 3) 9 2 int64


In [86]:
print(arr1.shape,arr1.size,arr1.ndim,arr1.dtype)
print(arr2.shape,arr2.size,arr2.ndim,arr2.dtype)
print(arr3.shape,arr3.size,arr3.ndim,arr3.dtype)

() 1 0 int64
(6,) 6 1 int64
(3, 3) 9 2 int64


Numpy expected behaviour is to have the symmetrical values inside array to retrun the results unlike assymetrical where the no of rows and columns are not equal passed inside the array
Here are the examples of symmetry and asymmetry to how numpy behaves 
Also please note numpy accepts only Homogenous values to generate matrices and arrays unlike asymmetrical values

In [96]:
#Here is an example of symmetrical numpy expected structure #
import numpy as np

arr10 = np.array([[1, 2, 3],
                    [4, 5, 6]])
print(arr10.shape)
print(arr10.size)
print(arr10.dtype)
print(arr10.ndim)

(2, 3)
6
int64
2


In [102]:
#Here is an example of the asymmetry numpy values which are invalid, even through the values are 2d/3d 
#but the no of rows are not equal to no of columns hence the axes does'nt get formed#
arr11 = np.array([[1, 2],
                     [3, 4, 5]])
print(arr11.shape)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [110]:
import numpy as np

arr12 = np.array([
    [[1], [2]],
    [[3], [4]]
])
print(arr12.shape)
print(arr12.size)
print(arr12.ndim)

(2, 2, 1)
4
3


In [114]:
#symmetry and asymmtery conceot #
b=np.array({2,3})
print(b.dtype)

object


In [156]:
arr2.reshape(4,2) # reshpae the output of array in to 3d or 4d dimension structure by using repshape command #

ValueError: cannot reshape array of size 6 into shape (4,2)

In [366]:
arr24=np.arange(18) #It provides array of numbers in list format# and convert it in to 3d using reshape functions
arr24

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [391]:
arr24.size

18

In [372]:
arr24.size
arr24.reshape(3,2,3) # 3 blocks, each block will have 2 rows and 3 columns)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])

In [405]:
a=np.array([[5,6,7,8],[3,2,4,5]])
a

array([[5, 6, 7, 8],
       [3, 2, 4, 5]])

In [407]:
a.reshape(2,2,2)

array([[[5, 6],
        [7, 8]],

       [[3, 2],
        [4, 5]]])

In [ ]:
# Built in array generators functions using numpy in python #
arange,zeros,ones,linspace,eye,random.rand,random.randint,

In [18]:
np.arange(1,7,2)

array([1, 3, 5])

In [395]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [376]:
np.arange(1,7) #it is exclusive of the start and end number #
z2=np.arange(100)

In [382]:
z2.size
z2.reshape(5,10,2) # 5block each block will have 10 rows and 2 columns#

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29],
        [30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49],
        [50, 51],
        [52, 53],
        [54, 55],
        [56, 57],
        [58, 59]],

       [[60, 61],
        [62, 63],
        [64, 65],
        [66, 67],
        [68, 69],
        [70, 71],
        [72, 73],
        [74, 75],
        [76, 77],
        [78, 79]],

       [[80, 81],
        [82, 83],
        [84, 85],
        [86, 87],
        [88, 89],
        [90, 91],
        [92, 93],
        [94, 95],
        [96, 97],
        [98, 99]]])

In [134]:
np.arange(1,7,2) # it is similiar to for in range concept)

array([1, 3, 5])

In [132]:
np.zeros((2,3,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [416]:
np.ones([10,2,5])  #Here we're passing 10 blocks, 2 rows and 5 columns)

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [138]:
np.ones(6)
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.linspace() # End point is inclusive by default when compared to any other function in numpy where it incldues the 10 value as well when we pass the range #

In [140]:
np.linspace(3,10)

array([ 3.        ,  3.14285714,  3.28571429,  3.42857143,  3.57142857,
        3.71428571,  3.85714286,  4.        ,  4.14285714,  4.28571429,
        4.42857143,  4.57142857,  4.71428571,  4.85714286,  5.        ,
        5.14285714,  5.28571429,  5.42857143,  5.57142857,  5.71428571,
        5.85714286,  6.        ,  6.14285714,  6.28571429,  6.42857143,
        6.57142857,  6.71428571,  6.85714286,  7.        ,  7.14285714,
        7.28571429,  7.42857143,  7.57142857,  7.71428571,  7.85714286,
        8.        ,  8.14285714,  8.28571429,  8.42857143,  8.57142857,
        8.71428571,  8.85714286,  9.        ,  9.14285714,  9.28571429,
        9.42857143,  9.57142857,  9.71428571,  9.85714286, 10.        ])

In [142]:
# Array functions is executed in float format #
#Generates 
np.linspace(3,10) #Generates a linear array of equally sapced count (default 50) of numbers between the range specified

array([[[ 3.        ,  3.14285714,  3.28571429,  3.42857143,
          3.57142857],
        [ 3.71428571,  3.85714286,  4.        ,  4.14285714,
          4.28571429],
        [ 4.42857143,  4.57142857,  4.71428571,  4.85714286,
          5.        ],
        [ 5.14285714,  5.28571429,  5.42857143,  5.57142857,
          5.71428571],
        [ 5.85714286,  6.        ,  6.14285714,  6.28571429,
          6.42857143]],

       [[ 6.57142857,  6.71428571,  6.85714286,  7.        ,
          7.14285714],
        [ 7.28571429,  7.42857143,  7.57142857,  7.71428571,
          7.85714286],
        [ 8.        ,  8.14285714,  8.28571429,  8.42857143,
          8.57142857],
        [ 8.71428571,  8.85714286,  9.        ,  9.14285714,
          9.28571429],
        [ 9.42857143,  9.57142857,  9.71428571,  9.85714286,
         10.        ]]])

In [422]:
arr = np.linspace(0, 1, 5)
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [418]:
np.linspace(2,3) # it include start and end valus where the result 

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [150]:
np.linspace(2,4).reshape(2,5,5) # To reshape the output in multiple diemnsional array #

array([[[2.        , 2.04081633, 2.08163265, 2.12244898, 2.16326531],
        [2.20408163, 2.24489796, 2.28571429, 2.32653061, 2.36734694],
        [2.40816327, 2.44897959, 2.48979592, 2.53061224, 2.57142857],
        [2.6122449 , 2.65306122, 2.69387755, 2.73469388, 2.7755102 ],
        [2.81632653, 2.85714286, 2.89795918, 2.93877551, 2.97959184]],

       [[3.02040816, 3.06122449, 3.10204082, 3.14285714, 3.18367347],
        [3.2244898 , 3.26530612, 3.30612245, 3.34693878, 3.3877551 ],
        [3.42857143, 3.46938776, 3.51020408, 3.55102041, 3.59183673],
        [3.63265306, 3.67346939, 3.71428571, 3.75510204, 3.79591837],
        [3.83673469, 3.87755102, 3.91836735, 3.95918367, 4.        ]]])

In [430]:
np.eye(2,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [154]:
np.eye(5) # Generates an identity matrix #

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [432]:
np.random.rand(2, 3)

array([[0.02724745, 0.20515944, 0.63227508],
       [0.2141037 , 0.77817999, 0.94602672]])

In [162]:
#rand,randn,randint
np.random.rand(4,20) #random float values between 0 and 1(1 is exclusive) in the shape specified

array([[0.39005924, 0.88931358, 0.56789835, 0.18657892, 0.11451653,
        0.23385836, 0.26387304, 0.49780849, 0.99209441, 0.99814023,
        0.43943772, 0.22509152, 0.98365879, 0.2305149 , 0.70969549,
        0.56733672, 0.71409941, 0.20113332, 0.7646232 , 0.57280239],
       [0.19506196, 0.30214925, 0.93737978, 0.92154436, 0.62517062,
        0.8048871 , 0.80410163, 0.57479629, 0.98385809, 0.9130502 ,
        0.20351596, 0.72626565, 0.54343457, 0.13774027, 0.17461353,
        0.72710846, 0.55872554, 0.25715644, 0.2552709 , 0.26261504],
       [0.58492611, 0.67103974, 0.07123607, 0.8156386 , 0.17369897,
        0.32746357, 0.84470552, 0.19430805, 0.34930911, 0.27690131,
        0.69223281, 0.40200904, 0.73309237, 0.89848284, 0.23507159,
        0.09286454, 0.25446109, 0.24284339, 0.82510495, 0.28406817],
       [0.2319116 , 0.7491392 , 0.40549593, 0.76121554, 0.31756529,
        0.17397185, 0.28120188, 0.85814636, 0.58020627, 0.82028322,
        0.80502489, 0.40806161, 0.16155844, 0

In [168]:
#It will generate random float values that belongs to STD standard deviation#
np.random,randn(3,5)

NameError: name 'randn' is not defined

In [434]:
np.random.randint(3,7,12) # Generates specified count of the values randonly between stop and start value)

array([5, 3, 5, 4, 3, 6, 6, 5, 6, 4, 3, 4])

In [ ]:
#Broadcasting
#aggregations
#np.where
#indexing
#slicing

In [ ]:
1.#Broadcasting #

In [172]:
#Broad casting is an attribute in numpy # it is 2 diemnsional array bases on the axes and no of list arrays passed
a1=np.array([[2,3,4],[4,5,6],[6,7,8]])
b1=np.array([5,6,7])

In [174]:
a1*b1  #broadcasting in numpy applies at element level since the arrays passed are in 2d/1d values #

array([[10, 18, 28],
       [20, 30, 42],
       [30, 42, 56]])

In [176]:
a1+b1

array([[ 7,  9, 11],
       [ 9, 11, 13],
       [11, 13, 15]])

In [184]:
#2.Aggregations on numpy arrays #
a = np.array([2,3,4,5,6,7,8,3,4,5,6,7,8,9])

In [186]:
np.min(a)

2

In [188]:
np.max(a)

9

In [190]:
# It will tell the index position of the minimum value #
np.argmin(a)

0

In [192]:
np.argmax(a) # It will tell the minimum 

13

In [194]:
np.median(a)

5.5

In [198]:
#Numpy conditions which is used as filter the elements and commonly used #
#np.where
#Gives the index values of the eleemnts that stasify the condition#
np.where(a%2==0)

(array([ 0,  2,  4,  6,  8, 10, 12]),)

In [200]:
#To fetch the element values# Herw we're using modulus operator #
a[np.where(a%2==0)]

array([2, 4, 6, 8, 4, 6, 8])

In [204]:
#Writing a filter using numpy to filter the values greater than 5 from the a variable #
a[np.where(a>5)] 

array([6, 7, 8, 6, 7, 8, 9])

In [206]:
np.where(a>5) #This would retrive the index positio of the values form the variable a #

(array([ 4,  5,  6, 10, 11, 12, 13]),)

In [ ]:
#INDEXING AND SLICING NUMPY ARRAY CONCEPT # it is used same as python concepts #

In [587]:
print(a)

[[5 6 7 8]
 [3 2 4 5]]


In [585]:
a

array([[5, 6, 7, 8],
       [3, 2, 4, 5]])

In [583]:
print(a[0:2])

[[5 6 7 8]
 [3 2 4 5]]


In [212]:
print(a[2:6])

[4 5 6 7]


In [599]:
d = np.random.randint(low=0, high=100, size=30)
d

array([87, 39, 12, 33, 78,  5, 62, 73,  1, 99,  6, 36, 56, 57, 66, 24, 18,
       76, 14, 32, 93, 87, 37, 50, 55, 83,  7, 21, 31, 98])

In [601]:
print(d[1:3])

[39 12]


In [605]:
print(d[:-1])

[87 39 12 33 78  5 62 73  1 99  6 36 56 57 66 24 18 76 14 32 93 87 37 50
 55 83  7 21 31]


In [607]:
print(d[:])

[87 39 12 33 78  5 62 73  1 99  6 36 56 57 66 24 18 76 14 32 93 87 37 50
 55 83  7 21 31 98]


In [633]:
d.reshape(5,3,2) #5*3*2 =30 (No of elements is equal to 30)

array([[[87, 39],
        [12, 33],
        [78,  5]],

       [[62, 73],
        [ 1, 99],
        [ 6, 36]],

       [[56, 57],
        [66, 24],
        [18, 76]],

       [[14, 32],
        [93, 87],
        [37, 50]],

       [[55, 83],
        [ 7, 21],
        [31, 98]]])

In [615]:
a1 = np.random.randint(2,20,30).reshape(2,3,5) # Each row is considered as 0 and starts 0 to 3#
a1

array([[[11,  9, 10,  8,  7],
        [14,  9, 16, 14, 15],
        [ 3,  8, 18,  6,  2]],

       [[15,  2,  4,  5,  9],
        [13,  8,  2, 18, 12],
        [ 8,  2, 10, 16, 15]]])

In [619]:
a1[0,1:3,2:5] #slicing multiple diemnsional arrays #
a1

array([[[11,  9, 10,  8,  7],
        [14,  9, 16, 14, 15],
        [ 3,  8, 18,  6,  2]],

       [[15,  2,  4,  5,  9],
        [13,  8,  2, 18, 12],
        [ 8,  2, 10, 16, 15]]])

In [629]:
a1[1,0:1,2:4]
a1

array([[[11,  9, 10,  8,  7],
        [14,  9, 16, 14, 15],
        [ 3,  8, 18,  6,  2]],

       [[15,  2,  4,  5,  9],
        [13,  8,  2, 18, 12],
        [ 8,  2, 10, 16, 15]]])

In [ ]:
#LIBRARY PANDAS #
#Pandas is alibrary that helps handle tabular data#
# Data in pandas is stored as dataframes, 2-d structure similiar to the tables in excel #
#Data Types in Pandas#
#1.series
#2.dataframe

#series in pandas is a 1-d data.
#dataframe is a 2d data so we dont have any other dimensional data in pandas unlike numpy such as 2d/3d/4d/5d -multi dimensions

In [20]:
#How do you create a series and dataframes in pandas
import pandas as pd
#A series can be constructed from list ,tuple,np.1d array, a dictionary but not set
a = pd.Series([1,2,3,4])
print(a)

0    1
1    2
2    3
3    4
dtype: int64


In [232]:
#Manually giving name to the indexes and series name # They are hidden values but we can name it using index and name keyword
ser1 =pd.Series((3,4,5,6),index=['row1','row2','row3','row4'],name='series1')
ser1

row1    3
row2    4
row3    5
row4    6
Name: series1, dtype: int64

#How do we create a dataframe in pandas #


In [ ]:
# Task:Create a pandas series with dictionary,a numpy array and a set.To observer how it is created #

In [244]:
#Creating dataframes in pandas#
#By default the rows and columns are numbered when executed in pandas dataframe #
import pandas as pd # not a number wher the 2d array null values are fille with nan #
#Pandas datafrane #
df = pd.DataFrame([[1,2,3,4,5],[5,6,7]])
df

0  1  2    3    4
0  1  2  3  4.0  5.0
1  5  6  7  NaN  NaN

In [641]:
df = pd.DataFrame([[1,2,3,4,5],[5,6,7]], index=['row1','row2'], columns = ['col1','col2','col3','col4','col5'])
df

col1  col2  col3  col4  col5
row1     1     2     3   4.0   5.0
row2     5     6     7   NaN   NaN

In [ ]:
#Functions in pandas # inplace keyword is used to apply the changes in dataframe so it is important to include index at the end of the code
Rename() to renmae the column name of the table 

In [258]:
df.rename(columns = {'col1':'c1'}, inplace=True) #Inplace =True - Ensure the permanent change is made to the dataframe table #

In [643]:
# INDEXING a dataframe value or row or a column #
df['col5']

row1    5.0
row2    NaN
Name: col5, dtype: float64

In [450]:
#Creating /adding new column in datafrane #
df['col7']
df.drop('col7', axis=1, inplace=True)

In [262]:
df[['c1' ,'col4']]

c1  col4
row1   1   4.0
row2   5   NaN

In [ ]:
# Locators and Iloc index locators #

In [657]:
#File reading in Pandas #
#Read csv is command 
df=pd.read_csv("/Users/akbarbasha/Desktop/train/train.csv")
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [ ]:
#Rows no will be added by default#
#Columns will auto populate based on the headers present in the csv file #

In [456]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [460]:
df.head(10) #default 5 records are printed however we can enter the custom value to show the no of records #

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [462]:
df.describe() # provides only the numerical headers #

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [464]:
df.describe(include ='object') #Fetches only the category column #

Name   Sex  Ticket    Cabin Embarked
count                       891   891     891      204      889
unique                      891     2     681      147        3
top     Braund, Mr. Owen Harris  male  347082  B96 B98        S
freq                          1   577       7        4      644

In [466]:
df.dtypes #It provides the datatype of the columns #

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [468]:
type(df)

pandas.core.frame.DataFrame

In [472]:
df.isnull().sum() #use aggrgation function to find the cound of null values #

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [478]:
df.Sex.unique()

array(['male', 'female'], dtype=object)

In [482]:
#value counts will tell the unique, overall count of the entries #
df.Sex.value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [486]:
#Locate a value in database #
df.Sex[3]

'female'

#Locators (Loc) and Index locators(iloc)

In [ ]:
### Locaters and Ilocaters
#Locaters are name based access of rows and columns.if rows are not named,row number also work
-df.loc[col_name,row_name]
-df/loc[row_no
-df.loc[[list of col name],[list of row_names]]
-df.loc[start_col:end_col, start_row:end_row]] Slicing cant happend because column name are not continous
## Indexlocaters 

In [492]:
df.loc[493,'Name']

'Artagaveytia, Mr. Ramon'

In [494]:
df.loc[493,:] #retrives the same row #it also retrives the same row

PassengerId                        494
Survived                             0
Pclass                               1
Name           Artagaveytia, Mr. Ramon
Sex                               male
Age                               71.0
SibSp                                0
Parch                                0
Ticket                        PC 17609
Fare                           49.5042
Cabin                              NaN
Embarked                             C
Name: 493, dtype: object

In [498]:
df.loc[493, ['Embarked','Name']] #using row no to fetch the column tables 

Embarked                          C
Name        Artagaveytia, Mr. Ramon
Name: 493, dtype: object

In [500]:
df.loc[4:15,['Embarked' ,'Name']]

Embarked                                               Name
4         S                           Allen, Mr. William Henry
5         Q                                   Moran, Mr. James
6         S                            McCarthy, Mr. Timothy J
7         S                     Palsson, Master. Gosta Leonard
8         S  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
9         C                Nasser, Mrs. Nicholas (Adele Achem)
10        S                    Sandstrom, Miss. Marguerite Rut
11        S                           Bonnell, Miss. Elizabeth
12        S                     Saundercock, Mr. William Henry
13        S                        Andersson, Mr. Anders Johan
14        S               Vestrom, Miss. Hulda Amanda Adolfina
15        S                   Hewlett, Mrs. (Mary D Kingcome)

In [ ]:
#Task
#Write a loc command to slice the rows 700-750, retrive name and ticket of the passengers#

In [689]:
df.loc[700:750,['Name','Ticket']]

Name             Ticket
700  Astor, Mrs. John Jacob (Madeleine Talmadge Force)           PC 17757
701                   Silverthorne, Mr. Spencer Victor           PC 17475
702                              Barbara, Miss. Saiide               2691
703                              Gallagher, Mr. Martin              36864
704                            Hansen, Mr. Henrik Juul             350025
705     Morley, Mr. Henry Samuel ("Mr Henry Marshall")             250655
706                      Kelly, Mrs. Florence "Fannie"             223596
707                  Calderhead, Mr. Edward Pennington           PC 17476
708                               Cleaver, Miss. Alice             113781
709  Moubarek, Master. Halim Gonios ("William George")               2661
710   Mayne, Mlle. Berthe Antonine ("Mrs de Villiers")           PC 17482
711                                 Klaber, Mr. Herman             113028
712                           Taylor, Mr. Elmer Zebley              19996
713                         Larsson, Mr. August Viktor               7545
714                              Greenberg, Mr. Samuel             250647
715         Soholt, Mr. Peter Andreas Lauritz Andersen             348124
716                      Endres, Miss. Caroline Louise           PC 17757
717                Troutt, Miss. Edwina Celia "Winnie"              34218
718                                McEvoy, Mr. Michael              36568
719                       Johnson, Mr. Malkolm Joackim             347062
720                  Harper, Miss. Annie Jessie "Nina"             248727
721                          Jensen, Mr. Svend Lauritz             350048
722                       Gillespie, Mr. William Henry              12233
723                            Hodges, Mr. Henry Price             250643
724                      Chambers, Mr. Norman Campbell             113806
725                                Oreskovic, Mr. Luka             315094
726        Renouf, Mrs. Peter Henry (Lillian Jefferys)              31027
727                           Mannion, Miss. Margareth              36866
728                    Bryhl, Mr. Kurt Arnold Gottfrid             236853
729                      Ilmakangas, Miss. Pieta Sofia   STON/O2. 3101271
730                      Allen, Miss. Elisabeth Walton              24160
731                           Hassan, Mr. Houssein G N               2699
732                               Knight, Mr. Robert J             239855
733                         Berriman, Mr. William John              28425
734                       Troupiansky, Mr. Moses Aaron             233639
735                               Williams, Mr. Leslie              54636
736            Ford, Mrs. Edward (Margaret Ann Watson)         W./C. 6608
737                             Lesurer, Mr. Gustave J           PC 17755
738                                 Ivanoff, Mr. Kanio             349201
739                                 Nankoff, Mr. Minko             349218
740                        Hawksford, Mr. Walter James              16988
741                      Cavendish, Mr. Tyrell William              19877
742              Ryerson, Miss. Susan Parker "Suzette"           PC 17608
743                                  McNamee, Mr. Neal             376566
744                                 Stranden, Mr. Juho  STON/O 2. 3101288
745                       Crosby, Capt. Edward Gifford          WE/P 5735
746                        Abbott, Mr. Rossmore Edward          C.A. 2673
747                              Sinkkonen, Miss. Anna             250648
748                          Marvin, Mr. Daniel Warner             113773
749                            Connaghton, Mr. Michael             335097
750                                  Wells, Miss. Joan              29103

In [502]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [512]:
#We cant slice columns because the column names are not consitent hence we use default column index locators for column indexing unlike row#
# we are using both the row and column indexing to retrieve the daat from the dataframe #
#iloc is more verstaile when compared to loc hence we 
df.iloc[[790,34,1],[3,6]] 

Name  SibSp
790                           Keane, Mr. Andrew "Andy"      0
34                             Meyer, Mr. Edgar Joseph      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...      1

In [663]:
# loc is used for filtering based on the conditions #
#Find all the passengers aged over 70 and their survival status #
df.loc[df.Age>70,['Name','Survived']]

Name  Survived
96              Goldschmidt, Mr. George B         0
116                  Connors, Mr. Patrick         0
493               Artagaveytia, Mr. Ramon         0
630  Barkworth, Mr. Algernon Henry Wilson         1
851                   Svensson, Mr. Johan         0

In [669]:
#find all the female passengers travelling alone where sibling and spouse column = 0 #
df.loc[(df.Sex=='female')&(df.SibSp==0)&(df.Parch==0),'Name']

2                                 Heikkinen, Miss. Laina
11                              Bonnell, Miss. Elizabeth
14                  Vestrom, Miss. Hulda Amanda Adolfina
15                      Hewlett, Mrs. (Mary D Kingcome) 
19                               Masselmani, Mrs. Fatima
                             ...                        
862    Swift, Mrs. Frederick Joel (Margaret Welles Ba...
865                             Bystrom, Mrs. (Karolina)
875                     Najib, Miss. Adele Kiamie "Jane"
882                         Dahlberg, Miss. Gerda Ulrika
887                         Graham, Miss. Margaret Edith
Name: Name, Length: 126, dtype: object

In [528]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [667]:
df.loc[(df.Sex=='male')&(df.SibSp==0)&(df.Parch==0),'Name']

4            Allen, Mr. William Henry
5                    Moran, Mr. James
6             McCarthy, Mr. Timothy J
12     Saundercock, Mr. William Henry
17       Williams, Mr. Charles Eugene
                    ...              
883     Banfield, Mr. Frederick James
884            Sutehall, Mr. Henry Jr
886             Montvila, Rev. Juozas
889             Behr, Mr. Karl Howell
890               Dooley, Mr. Patrick
Name: Name, Length: 411, dtype: object

In [685]:
#aggregation on databases -groupby combining with describe/head/info/
df.groupby('Sex').describe()

PassengerId                                                             \
             count        mean         std  min     25%    50%     75%    max   
Sex                                                                             
female       314.0  431.028662  256.846324  2.0  231.75  414.5  641.25  889.0   
male         577.0  454.147314  257.486139  1.0  222.00  464.0  680.00  891.0   

       Survived                                              Pclass            \
          count      mean       std  min  25%  50%  75%  max  count      mean   
Sex                                                                             
female    314.0  0.742038  0.438211  0.0  0.0  1.0  1.0  1.0  314.0  2.159236   
male      577.0  0.188908  0.391775  0.0  0.0  0.0  0.0  1.0  577.0  2.389948   

                                            Age                              \
            std  min  25%  50%  75%  max  count       mean        std   min   
Sex                                                                           
female  0.85729  1.0  1.0  2.0  3.0  3.0  261.0  27.915709  14.110146  0.75   
male    0.81358  1.0  2.0  3.0  3.0  3.0  453.0  30.726645  14.678201  0.42   

                                SibSp                                          \
         25%   50%   75%   max  count      mean       std  min  25%  50%  75%   
Sex                                                                             
female  18.0  27.0  37.0  63.0  314.0  0.694268  1.156520  0.0  0.0  0.0  1.0   
male    21.0  29.0  39.0  80.0  577.0  0.429809  1.061811  0.0  0.0  0.0  0.0   

             Parch                                                Fare  \
        max  count      mean       std  min  25%  50%  75%  max  count   
Sex                                                                      
female  8.0  314.0  0.649682  1.022846  0.0  0.0  0.0  1.0  6.0  314.0   
male    8.0  577.0  0.235702  0.612294  0.0  0.0  0.0  0.0  5.0  577.0   

                                                                      
             mean        std   min        25%   50%    75%       max  
Sex                                                                   
female  44.479818  57.997698  6.75  12.071875  23.0  55.00  512.3292  
male    25.523893  43.138263  0.00   7.895800  10.5  26.55  512.3292

In [683]:
pd.set_option('display.max_rows',None) # We set this to display the overall column group by values otherwise by default only 5 rows/columns#
pd.set_option('display.max_columns',None)

In [687]:
# We set this to display the overall column group by values otherwise by default only 5 rows/columns#
pd.reset_option('display.max_rows',None) 
pd.reset_option('display.max_columns',None)

In [546]:
#aggregation on databases -groupby combining with describe/head/info/
df.groupby('Sex').describe()

PassengerId                                                             \
             count        mean         std  min     25%    50%     75%    max   
Sex                                                                             
female       314.0  431.028662  256.846324  2.0  231.75  414.5  641.25  889.0   
male         577.0  454.147314  257.486139  1.0  222.00  464.0  680.00  891.0   

       Survived                                              Pclass            \
          count      mean       std  min  25%  50%  75%  max  count      mean   
Sex                                                                             
female    314.0  0.742038  0.438211  0.0  0.0  1.0  1.0  1.0  314.0  2.159236   
male      577.0  0.188908  0.391775  0.0  0.0  0.0  0.0  1.0  577.0  2.389948   

                                            Age                              \
            std  min  25%  50%  75%  max  count       mean        std   min   
Sex                                                                           
female  0.85729  1.0  1.0  2.0  3.0  3.0  261.0  27.915709  14.110146  0.75   
male    0.81358  1.0  2.0  3.0  3.0  3.0  453.0  30.726645  14.678201  0.42   

                                SibSp                                          \
         25%   50%   75%   max  count      mean       std  min  25%  50%  75%   
Sex                                                                             
female  18.0  27.0  37.0  63.0  314.0  0.694268  1.156520  0.0  0.0  0.0  1.0   
male    21.0  29.0  39.0  80.0  577.0  0.429809  1.061811  0.0  0.0  0.0  0.0   

             Parch                                                Fare  \
        max  count      mean       std  min  25%  50%  75%  max  count   
Sex                                                                      
female  8.0  314.0  0.649682  1.022846  0.0  0.0  0.0  1.0  6.0  314.0   
male    8.0  577.0  0.235702  0.612294  0.0  0.0  0.0  0.0  5.0  577.0   

                                                                      
             mean        std   min        25%   50%    75%       max  
Sex                                                                   
female  44.479818  57.997698  6.75  12.071875  23.0  55.00  512.3292  
male    25.523893  43.138263  0.00   7.895800  10.5  26.55  512.3292

In [548]:
df.groupby('Sex').Age.mean()

Sex
female    27.915709
male      30.726645
Name: Age, dtype: float64

In [572]:
#sorting a dataframe # sort the values 
df.sort_values('Age')
df.sort_values('Age',ignore_index=True) #This returns new values based on the Age sorted column#
df.sort_values('Age',inplace = True) #This modifies the entire dataframe because we Inplace =True along with sorting#

PassengerId  Survived  Pclass                                      Name  \
0            804         1       3           Thomas, Master. Assad Alexander   
1            756         1       2                 Hamalainen, Master. Viljo   
2            645         1       3                    Baclini, Miss. Eugenie   
3            470         1       3             Baclini, Miss. Helene Barbara   
4             79         1       2             Caldwell, Master. Alden Gates   
..           ...       ...     ...                                       ...   
886          860         0       3                          Razi, Mr. Raihed   
887          864         0       3         Sage, Miss. Dorothy Edith "Dolly"   
888          869         0       3               van Melkebeke, Mr. Philemon   
889          879         0       3                        Laleff, Mr. Kristo   
890          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   

        Sex   Age  SibSp  Parch      Ticket     Fare Cabin Embarked  
0      male  0.42      0      1        2625   8.5167   NaN        C  
1      male  0.67      1      1      250649  14.5000   NaN        S  
2    female  0.75      2      1        2666  19.2583   NaN        C  
3    female  0.75      2      1        2666  19.2583   NaN        C  
4      male  0.83      0      2      248738  29.0000   NaN        S  
..      ...   ...    ...    ...         ...      ...   ...      ...  
886    male   NaN      0      0        2629   7.2292   NaN        C  
887  female   NaN      8      2    CA. 2343  69.5500   NaN        S  
888    male   NaN      0      0      345777   9.5000   NaN        S  
889    male   NaN      0      0      349217   7.8958   NaN        S  
890  female   NaN      1      2  W./C. 6607  23.4500   NaN        S  

[891 rows x 12 columns]

In [ ]:
#Changing the datatype of the columns# Downcasting concept where we change the size of column with 1 and 0 to int8 to improve 
#Pandas for fasting querying and performance #

In [554]:
#using downcast, astype() function and to_numeric function for converting the datatypes of the colukns to reduce memory waste for computing#
df.Pclass = df.Pclass.astype('object') #Pclass column bytes has been updated from int64 to int8 since it is 1,0 values#
df.Pclass =pd.to_numeric(df.Pclass,downcast='integer') #Here we use the downcast for datatype conversion#

In [558]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [576]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass            int8
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [ ]:
#Cleaning the data and manipulating the data # We use it for data transformations#
#NUMPY AND PANDAS SIGNFICANCE STEP in performing clening operaions #
#Transformation
#De-duplication-Removing duplicates
#Removing columns
#Imputing Values

In [578]:
#It will remove duplicates from the table by default using this keyword #
#It elimintaes duplicates values from the table#
#Both the above commands has default inplace =true where it makes permananent change to the dataframe table
# so we need to use inplace=True, while working on real based data cleaning scenarios #
df.drop_duplicates() #It will drop the entire row even one of the 

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [ ]:
#Using drop na command will drop the rows from the entire table
#Inplace is not used hence we are not altering the dataframe to submit the changes#
df.dropna()

In [ ]:
#Value imputing#
#Inplace command is used with this command as well#
df.fillna() #Filling the na values with the text "unknown" or passing zero values will take afffect once we use inplace=True Parameter# 
#Best practice# To use the value keyword and specify the insert values to each of the na cells column#
df.fillna(value={'Sex':'male','Cabin':'Nothing'},inplace=True)
#Inplace is essential while making changes since this would update the dataframe#

In [ ]:
#using loc method to fill na values where inplace is not required #Filling the values with the mean so that it is ND spread for analysis#
df.loc[df.Age.isnull(),'Age']] = df.Age.mean()

In [ ]:
#dropping a column#We need to use inplace argument to make permanenet chnages in the table #
df.drop['Age'],axis=1,inplace=True)

In [580]:
#Transformation with Pandas #
df['Family'] = df.SibSp + df.Parch

In [ ]:
# DOCKER CONTAINERZATION #